
  - name: be sure libselinux-python are installed
    yum: name=libselinux-python state=present update_cache=yes
    when: "ansible_os_family == 'RedHat'"

  - name: install libselinux-python ubuntu
    apt: name=libselinux-python state=present
    when: "ansible_os_family == 'Debian'"

  # - name: install joe repo6
  #   yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=present validate_certs=False
  #   when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

  # - name: install joe repo7
  #   yum: name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm state=present
  #   when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  - name: Install EPEL repo.
    yum:
      name: "{{ epel_repo_url }}"
      state: present
      validate_certs: false
      update_cache: yes
    register: result
    until: '"failed" not in result'
    retries: 1
    delay: 5

  # - name: Import EPEL GPG key.
  #   rpm_key:
  #     key: "{{ epel_repo_gpg_key_url }}"
  #     state: present

  - name: install packages
    yum: name={{ item }} state=present update_cache=yes
    with_items:
      - joe
      - nano
      - wget
      - htop
      - telnet
      - tcpdump
      - smem
      - screen
      - gcc
      - nc
      - mutt
      - vim
      - ntp
      - rsync
    ignore_errors: yes


  - name: install and run ntp
    yum: name=ntp state=present 

  - name: active ntp service
    service: name=ntpd state=started enabled=yes





