- debug: var=ec2_access_key 

- name: provision ec2 t2.micro centos 7
  ec2: 
    region: "{{aws_region}}"
    key_name: "{{ec2_key}}"
    instance_type: t2.micro
    image: "{{ec2_amid_centos7}}"
    wait: yes
    instance_tags:
      Name: test
    count: 1
    #vpc_subnet_id: "{{ec2_vpc_default}}"
    #assign_public_ip: yes
  register: ec2




- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} groups=ec2hosts
  with_items: "{{ ec2.instances }}"